@startuml
start
partition 插入boss订单记录表(TS_BOSS_ORDER_RECORD) {
	:每次请求boss关系同步，都会插入一条记录详情,插入以下字段;
	note right
	TRANSACTION_ID 阳光计划订单编号;
	OPER_CODE 操作码01 – 业务开通;
	SP_CODE sp_Code;
	SPSERV_CODE 业务代码;
	CHANNEL_CODE 渠道代码;
	USER_ID 用户ID;
	MSISDN 用户标识;
	PHONENUMBER 手机号;
	EXECUTION_STATUS 2:未执行(1:执行成功;2:未执行;3:兑书卡生成失败;4:订购尊享卡失败;5:调SMU失败;6:操作订单失败;7:操作订购记录失败);
	ORIGIN_ORDER_ID 咪咕侧订购包月业务受理流水号;
	OPER_TIME 操作时间;
	end note
}
:根据用户标识、新的会员类型Id查询TS_MONTHLY_ORDER_RECORD最新的连续包月订购记录;
:如果用户连续包月订购记录不为空,且订购记录的到期时间晚于当前时间,将orderType变量设为7;
if (连续包月订购记录不为空)then(true)
    if(订购关系中OPER_TIME时间为空 或者 BOSS通知中的OPER_TIME时间>订购关系中OPER_TIME时间)then(true)
        if (入参operCode 为 01)then(true)
            if (入参originOrderId 不为空)then(true)
                :根据originOrderId当做TRANSACTION_ID去TS_MONTHLY_ADVANCE_PAY连续包月支付记录;
                if (支付记录 不为空)then(true)
                    :更新TS_MONTHLY_ADVANCE_PAY连续包月支付记录 SUB_PAY_STATUS为2支付成功;
                else
                    :未查询相应的订单时，则不进行操作;
                    stop;
                endif
            else
                partition 插入连续包月支付表(TS_MONTHLY_ADVANCE_PAY) {
                    :插入以下字段;
                    note right
                    CHANNEL_CODE 合作方渠道代码 00手动调用接口补发会员
                    CLIENT_TYPE 0其他
                    MONTHLY_PRICE 包月价格
                    MSISDN 用户标识
                    USER_ID 用户Id
                    PHONENUMBER 手机号
                    OBJECT_ID 包月Id
                    OPER_CODE 01 – 业务开通
                    SHOPPE_ID
                    SP_CODE
                    SUB_PAY_STATUS 2支付成功
                    TRANSACTION_ID 阳光计划订单编号
                    ORDER_CHANNEL 订购渠道 1boss订购
                    end note
                }
            endif

            :根据连续包月记录的主键Id、用户Id、当前月份(格式"yyyyMM")、会员类型为1连续包月
            查询TS_MONTHLY_ORDER_DETAIL每月订购记录的主键Id;
            if (每月订购记录的主键Id 不为空)then(true)
                :更新TS_MONTHLY_ORDER_DETAIL每月订购记录 ORDER_STATUS为1订购;
            else
                partition 插入每月订购记录表(TS_MONTHLY_ORDER_DETAIL) {
                :插入以下字段;
                note right
                VIP_ORDER_ID 连续包月表主键
                MONTHLY_ID 连续包月表包月Id
                ORDER_CHANNEL 连续包月表的订购渠道
                USER_ID 连续包月表的用户Id
                PAY_WAY 连续包月表的支付方式
                VIP_TYPE 1连续包月
                MONTH 当前月份格式"YYYYMM"
                end note
            }
            endif
            partition 通过当前手机号校验能否下发兑书卡 {
                :根据sys_key为END_MONTHLY_UNABLE_ORDER_SWITCH 去TS_SYSTEM_PARAM查询是否启动江苏无计费管控 0关闭 1打开;
                if (开关 为空 或 为1)then(true)
                    :校验开关 为开;
                endif
                partition 当前时间是否在配置的时间内 {
                    :根据sys_key为END_MONTHLY_UNABLE_ORDER_TIME_QUANTUM 去TS_SYSTEM_PARAM查询江苏无计费管控需要管控的时间段 23:00:00-23:59:59;
                    :根据sys_key为TEST_REPLACE_TIME_SWITCH 去TS_SYSTEM_PARAM查询值 0关闭 1打开 仅供测试使用，打开时会替换当前时间为当月最后一天的最后一秒;
                    if (值为1打开)then(true)
                        :当前时间为当月最后一天的最后一秒;
                    else
                        :当前时间为当前时间;
                    endif
                    if (当前时间在管控的时间段内)
                        :返回true;
                    else
                        :返回false;
                    endif
                }
                if (校验开关 为开 且 当前时间在配置的时间内)then(true)
                    :校验手机号为true;
                endif
                partition 校验是否是江苏省号码 {
                    :根据province_id为250、number_segment为手机号查询CIS_T_NUMBER_SEGMENT的总条数;
                    if (总条数 > 0)then(true)
                        :返回true;
                    else
                        :返回false;
                    endif
                }
                if (校验手机号为true 且 校验是江苏省号码)then(true)
                    :返回不能发兑书卡;
                endif
            }

            if (当前手机号校验能下发兑书卡 且 用户类型为1正常用户(收货地址表的省份不为"外蒙古"))then(true)
                :定义key 为 "GIVE_EXCHANGE_CARD"+用户Id+包月id;
                if(redis 不存在 key)then(true)
                    :存入redis key:key value:key 过期时间 10s;
                    partition 查询本月下发的兑书卡 {
                        :查询正常下发的兑书卡;
                        note right
                        根据 用户id、
                        包月Id、
                        转赠类型为空、
                        创建时间为本月、
                        状态 不为4:失效或9:包月退订失效、
                        订购类型为1:订购, 2:自动续订, 5:对账订购, 6:对账续订, 7:手工续订, 33:小学阅读卡, 39:城市代理阅读卡, 55:樊登联合推广
                        的记录列表
                        end note
                        :查询转赠下发的兑书卡;
                        note right
                        根据 用户id、
                        包月Id、
                        转赠类型为1赠送、
                        创建时间为本月、
                        订购类型为1:订购, 2:自动续订, 5:对账订购, 6:对账续订, 7:手工续订, 33:小学阅读卡, 39:城市代理阅读卡, 55:樊登联合推广
                        的记录列表
                        end note
                        :返回两者的并集;
                    }
                    if (需要下发兑书卡数量(TS_MONTHLY_SET包月配置表对应产品的兑书卡下发数量) > 本月下发的兑书卡的数量)then(true)
                        partition 下发兑书卡 {
                            :组装下发兑书卡参数;
                            note right
                            userId = userId
                            msisdn = msisdn
                            monthlyId = TS_MONTHLY_SET包月配置表对应产品的包月Id
                            displayFlag = 包月价格为8、29、68 的为2不展示，其他为1展示
                            effectiveTimeNum = TS_MONTHLY_SET包月配置表对应产品的兑书卡有效期
                            effectiveTimeType = TS_MONTHLY_SET包月配置表对应产品的兑书卡有效类型
                            num = 需要下发兑书卡数量 - 本月下发的兑书卡的数量
                            orderType = 1订购
                            channelCode = 入参渠道号
                            payWay = 2
                            monthlyOrderDetailId = TS_MONTHLY_ORDER_DETAIL每月订购记录的主键Id
                            end note
                            if (有效期类型 为1日)then(true)
                                :有效期为 当前时间 + 有效期对应天数;
                            else if (有效期类型 为2月)then(true)
                                :有效期为 当前时间 + 有效期对应月数;
                            else if (有效期类型 为3年)then(true)
                                :有效期为 当前时间 + 有效期对应年数;
                            else
                                :抛出有效期类型错误;
                            endif
                            if (num 不为0)then(true)
                                :定义i=0,ids集合;
                                while (i < num) is (true)
                                    :根据序列SEQ_ENTITY_CARD_ID创建兑书卡Id,并加入ids集合;
                                    :i++;
                                end while(false)
                            endif
                            partition 遍历兑书卡ids集合 {
                                partition 插入兑书卡表(TS_ENTITY_CARD_GIVEN) {
                                    :插入以下字段;
                                    note right
                                    DISPLAY_FLAG 展示标志，1：展示，2：不展示
                                    EFFECTIVE_TIME 有效期
                                    ENTITY_CARD_ID 兑书卡Id
                                    MONTHLY_ID TS_MONTHLY_SET包月配置表对应产品的包月Id
                                    ORDER_TYPE 1:订购
                                    STATUS 1未使用
                                    USER_ID 用户Id
                                    MONTHLY_ORDER_DETAIL_ID 每月订购记录表的主键Id
                                    end note
                                    note right
                                    一个每月订购记录表的主键Id对应1或2个兑书卡记录，当前不可能大于两条记录
                                    end note
                                }
                            }
                        }
                    endif
                endif
            endif
            partition 更新连续包月记录表(TS_MONTHLY_ORDER_RECORD) {
                                                :更新以下字段;
                                                note right
                                                MEMBER_PRODUCT_ID 新的产品Id 根据包月Id、场景类型2连续包月去MEMBER_PRODUCT_MONTHLY查询新的产品Id
                                                PAY_WAY 6 话费
                                                ORDER_CHANNEL 订购渠道1 boss
                                                SP_CODE
                                                IS_EXTENSION 用户标识 0:推广用户;1:正常用户
                                                TRANSACTION_ID 阳光计划订单编号
                                                ORDER_STATUS 1:已订购
                                                END_TIME 失效时间 2099年01月01号
                                                START_TIME 当月1号
                                                SUB_TIME 当前时间
                                                OPER_TIME boss订单记录的操作时间
                                                end note
           }
        endif
	endif
endif
stop
@enduml